--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Inaay/Killstreak
build-by-default: true
branches:
- main
projects:
  Killstreak:
    icon: meta/Logo.png
    path: ""
    lint:
      phpstan: false
...
